%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% This code DON'T compute data base, ONLY plots curves for Figure 3.6
% Follow the steps:
% 1) Run the code Fig3_6.m to generate data; 
% 2) Run this code.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%-------------------------------------------------------------------------
% Initialization
%-------------------------------------------------------------------------

close all

%---------------------------------------------------------------------
% Plotting
%--------------------------------------------------------------------- 
figure(1)

% Colors for each "m" curve: "light blue", "light orange and "red"";
colors = [ [71, 147, 175]; [255, 196, 112]; [221, 87, 70] ]/255;

curveSIR = zeros(length(N));
for kn = 1:length(N)
    for km = 1:length(m)
        curveSIR(kn) = plot(U, squeeze(mult_gain(kn,km,:)),'s-' , ...
            'MarkerSize',10, 'Color',colors(kn,:), 'Linewidth', 2);
        hold on;
    end
end
curveSIR_opt = plot( uoptimal, mult_gain_opt, 'p', 'MarkerSize',18, ...
    'MarkerEdgeColor','r', 'MarkerFaceColor',[1 .6 .6],'LineWidth',2 );


%-------------------------------------------------------------------------
% Set figure parameters
%------------------------------------------------------------------------

grid on;
xlabel( 'Number of Users - $U$', 'Interpreter', 'Latex', 'FontSize', 24 );
ylabel( 'Multiplexing Gain - $\mathcal{G}_m$', 'Interpreter', 'Latex', 'FontSize', 24 );
xticks([2,4,6,8])
ylim( [0, 4] );
yticks([0,1,2,3,4])
set(gca, 'TickLabelInterpreter', 'latex','FontSize',24) 

legend([curveSIR(1), curveSIR(2), curveSIR(3),curveSIR_opt(1,1)],...
    {['$N = $ ',num2str(N(1))], ['$N = $ ',num2str(N(2))], ['$N = $ ',num2str(N(3))], '$\mathcal{G}_m(U^{\star})$'},...
    'Interpreter', 'Latex', 'FontSize', 24,'NumColumns',1, Location='northeast');

% Create textbox: parameters
annotation(figure(1),'textbox',...
    [0.78 0.52 0.10 0.10],...   
    'String',['$\gamma= $ ',num2str(gamdB),' dB', newline,'$W=$ ',num2str(W)],...
    'Interpreter','latex','FontSize',24,'HorizontalAlignment','center');

% Create textbox m = 1
annotation(figure(1),'textbox',...
    [0.446,0.783,0.0846,0.0373],...
    'String','$m = 1$',...
    'Interpreter','latex',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);
annotation(figure(1),'ellipse',...
    [0.414,0.6006,0.021,0.219]);

% Create textbox m = 2
annotation(figure(1),'textbox',...
    [0.316,0.535,0.0846,0.03733],...
    'String','$m = 2$',...
    'Interpreter','latex',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);
annotation(figure(1),'ellipse',...
    [0.2906,0.3951,0.02028,0.166]);

% Create textbox m = 3
annotation(figure(1),'textbox',...
    [0.1487,0.2216,0.0846,0.0373],...
    'String',{'$m = 3$'},...
    'Interpreter','latex',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);
annotation(figure(1),'ellipse',...
    [0.2123,0.2675,0.0203,0.15]);
