%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This code DON'T compute data base, ONLY plots curves for Figure 4.1
% Follow the steps:
% 1) Run the code Fig4_1.m to generate data; 
% 2) Run this code.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

close

%---------------------------------------------------------------------
% Plotting
%--------------------------------------------------------------------- 
figure(1)

% Colors for SINR curves: "light orange" and "light blue";
colors = ['b';'r'];

for kw = length(W):-1:1
    for kfama = length(famatype):-1:1
        curveINT(kw) = semilogy(N, squeeze(pout_calc_int(:,kw,kfama)), 'Color', colors(kw,:), 'linewidth', 4);
        hold on;
        curveINT_blocks(kw) = semilogy(N, squeeze(pout_calc_int_blocks(:,kw,kfama)), 'Color', colors(kw,:), 'linewidth', 4);
        curveGL = semilogy(Nsimul,squeeze(pout_calc_gl(:,kw,kfama)), 's', 'Color', 'r', 'linewidth', 4,'MarkerSize', 10);
        curveGL_blocks = semilogy(Nsimul,squeeze(pout_calc_gl_blocks(:,kw,kfama)), 's', 'Color', 'r', 'linewidth', 4,'MarkerSize', 10);
        curveSIM = semilogy(Nsimul, squeeze(pout_sim(:,kw,kfama)), '+', 'Color', 'k', 'linewidth', 4,'MarkerSize', 10);
        curveSIM_blocks = semilogy(Nsimul, squeeze(pout_sim_blocks(:,kw,kfama)), '+', 'Color', 'k', 'linewidth', 4,'MarkerSize', 10);
    end
end

%-------------------------------------------------------------------------
% Set figure parameters
%------------------------------------------------------------------------

grid on;
xlabel( 'Number of Ports $- \, N$', 'Interpreter', 'Latex', 'FontSize', 24 );
ylabel( 'Outage Probability', 'Interpreter', 'Latex', 'FontSize', 24 );
xlim( [20, 200] );
ylim( [6e-6, 1] );
set(gca, 'TickLabelInterpreter', 'latex','FontSize',24) 

legend([curveINT(1), curveINT(2), curveGL, curveSIM],...
    { ['$W = $ ', num2str(W(1))], ['$W = $ ',num2str(W(2))], 'Gauss-Laguerre','Simulation'},...
    'Interpreter', 'Latex', 'FontSize', 24, 'NumColumns',1, Location='east');

% Create textbox: parameters
annotation(figure(1),'textbox',...
    [0.619879746835443,0.12779552715655,0.155436708860759,0.119919062832801],...   
    'String',['$U=$ ',num2str(U), newline ...
    '$m = $ ', num2str(m), newline,...
    '$\gamma= $ ',num2str(gamdB),' dB'],...
    'Interpreter','latex',...
    'BackgroundColor','w',...
    'HorizontalAlignment','center',...
    'FontSize',24,...
    'FitBoxToText','off');


%-------------------------------------------------------------------------
% Annotion boxes
%------------------------------------------------------------------------

%------------------------------------------------------------------------
% Spatial-block correlation s-FAMA:
% Create ellipse
annotation(figure(1),'ellipse',...
    [0.4558, 0.760, 0.0394, 0.133]);
% Create textbox
annotation(figure(1),'textbox',...
    [0.4917, 0.8444, 0.125, 0.074],...
    'String',{'Block Corr.','$s$-FAMA'},...
    'Interpreter','latex',...
    'FontSize',20,...
    'FitBoxToText','off',...
    'EdgeColor','none');
%------------------------------------------------------------------------


%------------------------------------------------------------------------
% Spatial-block correlation f-FAMA:
% Create ellipse
annotation(figure(1),'ellipse',...
    [0.454, 0.475, 0.0394, 0.252]);
% Create textbox
annotation(figure(1),'textbox',...
    [0.355, 0.566, 0.125, 0.074],...
    'String',{'Block Corr.','$f$-FAMA'},...
    'Interpreter','latex',...
    'HorizontalAlignment','right',...
    'FontSize',20,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1],...
    'BackgroundColor',[1 1 1]);
%------------------------------------------------------------------------


%------------------------------------------------------------------------
% Const correl s-FAMA:
% Create ellipse
annotation(figure(1),'ellipse',...
    [0.255879746835443,0.313099041533547,0.424,0.074835995740151]);
% Create textbox
annotation(figure(1),'textbox',...
    [0.3576,0.346,0.125,0.074],...
    'String',{'Cte. Corr.','$s$-FAMA'},...
    'Interpreter','latex',...
    'FontSize',20,...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1],...
    'EdgeColor',[1 1 1]);
%------------------------------------------------------------------------


%------------------------------------------------------------------------
% Const correl f-FAMA:
% Create ellipse
annotation(figure(1),'ellipse',...
    [0.1306,0.1629,0.221,0.113]);
% Create textbox
annotation(figure(1),'textbox',...
    [0.1855,0.175,0.124,0.074],...
    'String',{'Cte. Corr.','$f$-FAMA'},...
    'Interpreter','latex',...
    'FontSize',20,...
    'EdgeColor',[1 1 1]);
%------------------------------------------------------------------------


