%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This code DON'T compute data base, ONLY plots curves for Figure 3.3
% Follow the steps:
% 1) Run the code Fig3_3.m to generate data; 
% 2) Run this code.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%-------------------------------------------------------------------------
% Initialization
%-------------------------------------------------------------------------

close all

%---------------------------------------------------------------------
% Plotting
%--------------------------------------------------------------------- 
figure(1)


% Colors for each "N" curve: "light organge and "light blue",;
colors = [  [ 255, 196, 110];  [71,147,175]; ]/255;

for kn = length(N):-1:1
    for ku = length(U):-1:1
        curveSIR = semilogy(avg_snrdB, squeeze(pout_calc_sir(kn,ku,:)), '--', 'Color','r', 'Linewidth', 3);
        hold on;
        curveINT(kn) = semilogy(avg_snrdB, squeeze(pout_calc_int(kn,ku,:)), 'Color', colors(kn,:), 'linewidth', 4);
        curveGL = semilogy(avg_snr_simdB,squeeze(pout_calc_gl(kn,ku,:)), 's', 'Color', 'r', 'linewidth', 3, 'MarkerSize', 10);
        curveSIM = semilogy(avg_snr_simdB, squeeze(pout_sim(kn,ku,:)), '+', 'Color', 'k', 'linewidth', 3,'MarkerSize', 10);
    end
end

%-------------------------------------------------------------------------
% Set figure parameters
%------------------------------------------------------------------------

grid on;
xlabel( 'Average SNR (dB)', 'Interpreter', 'Latex', 'FontSize', 24 );
ylabel( 'Outage Probability', 'Interpreter', 'Latex', 'FontSize', 24 );
xlim( [-10, 25] );
ylim( [1e-6, 1] );
set(gca, 'TickLabelInterpreter', 'latex','FontSize',24) 

legend([curveSIR, curveINT(1), curveINT(2), curveGL, curveSIM],...
    {'SIR', ['SINR, $N = $ ', num2str(N(1))],...
    ['SINR, $N = $ ',num2str(N(2))], 'Gauss-Laguerre','Simulation'},...
    'Interpreter', 'Latex', 'FontSize', 24, 'NumColumns',2, Location='south');

% Create textbox: parameters
annotation(figure(1),'textbox',...
    [0.1576,0.4896,0.1179,0.139],...   
    'String',['$m = $ ', num2str(m), newline,...
    '$W=$ ',num2str(W), newline,...
    '$\gamma= $ ',num2str(gamdB),' dB'],...
    'Interpreter','latex',...
    'FontSize',24,...
    'HorizontalAlignment','center',...
    'FitBoxToText','on');

%-------------------------------------------------------------------------
% Annotion boxes
%------------------------------------------------------------------------

% Create ellipse U = 3
annotation(figure(1),'ellipse',...
    [0.74, 0.325, 0.028, 0.15,]);
% Create ellipse U = 4
annotation(figure(1),'ellipse',...
    [0.74, 0.642, 0.024, 0.0969]);
% Create ellipse U = 5
annotation(figure(1),'ellipse',...
    [0.74, 0.805, 0.0208, 0.0714]);


% Create textbox U = 3
annotation(figure(1),'textbox',...
    [0.78, 0.455, 0.0846, 0.0373],...
    'String','$U = 3$',...
    'Interpreter','latex',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox U = 4
annotation(figure(1),'textbox',...
    [0.78 0.735, 0.0846, 0.0373],...
    'String','$U = 4$',...
    'Interpreter','latex',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox U = 5
annotation(figure(1),'textbox',...
    [0.78, 0.867, 0.0846, 0.0373],...
    'String',{'$U = 5$'},...
    'Interpreter','latex',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

