%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This code DON'T compute data base, ONLY plots curves for Figure 3.2
% Follow the steps:
% 1) Run the code Fig3_2.m to generate data; 
% 2) Run this code.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%-------------------------------------------------------------------------
% Initialization
%-------------------------------------------------------------------------

close all

%---------------------------------------------------------------------
% Plotting
%--------------------------------------------------------------------- 
figure(1)

for km = length(m):-1:1

    curveSIR = semilogy(avg_snrdB, pout_calc_sir(km,:), '--', 'Color','r', 'Linewidth', 3);
    hold on; 
    curveINT = semilogy(avg_snrdB, pout_calc_int(km,:), 'Color', [71,147,175]/255, 'linewidth', 4);
    curveGL = semilogy(avg_snrdB, pout_calc_gl(km,:), 's', 'Color', 'r', 'linewidth', 3, 'MarkerSize', 10);
    curveSIM = semilogy(avg_snrdB, pout_sim(km,:), '+', 'Color', 'k', 'linewidth', 3,'MarkerSize',10);

end

%-------------------------------------------------------------------------
% Set figure parameters
%------------------------------------------------------------------------

grid on;
xlabel( 'Average SNR (dB)', 'Interpreter', 'Latex', 'FontSize', 24 );
ylabel( 'Outage Probability', 'Interpreter', 'Latex', 'FontSize', 24 );
xlim( [-10, 25] );
ylim( [1e-3, 1] );
set(gca, 'TickLabelInterpreter', 'latex','FontSize',24) 

% Create Legend
legend( [curveSIR, curveINT, curveSIM, curveGL],...
    {'SIR', 'SINR', 'Simulation', 'Gauss-Laguerre'}, ...
    'Interpreter', 'Latex', 'FontSize', 24, Location='east' );

% Create textbox: parameters
annotation(figure(1),'textbox',...
    [0.144,0.396,0.129,0.1778],...
    'String',['$N = $ ', num2str(N), newline,...
    '$W=$ ',num2str(W), newline,...
    '$U=$ ',num2str(U),newline,...
    '$\gamma= $ ',num2str(gamdB),' dB'],...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',24,...
    'FitBoxToText','on');

% Create ellipse m = 1
annotation(figure(1),'ellipse',...
    [0.5236, 0.216, 0.0264, 0.135]);
% Create ellipse m = 2
annotation(figure(1),'ellipse',...
    [0.566, 0.579, 0.0240, 0.0937]);
% Create ellipse m = 3
annotation(figure(1),'ellipse',...
    [0.650, 0.745, 0.0200, 0.0724]);

% Create textbox m = 1
annotation(figure(1),'textbox',...
    [0.438, 0.240, 0.1, 0.0515],...
    'String',{'$m=1$'},...
    'Interpreter','latex',...
    'FontSize',24,...
    'EdgeColor',[1 1 1]);

% Create textbox m = 2
annotation(figure(1),'textbox',...
    [0.477, 0.5469, 0.1 0.0515],...
    'String',{'$m=2$'},...
    'Interpreter','latex',...
    'FontSize',24,...
    'EdgeColor',[1 1 1]);

% Create textbox m = 3
annotation(figure(1),'textbox',...,
    [0.621, 0.810 0.1 0.0515],...
    'String',{'$m=3$'},...
    'Interpreter','latex',...
    'FontSize',24,...
    'EdgeColor',[1 1 1]);
